// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0oDjc489B4AmTYfmJfarpaFoX1rbVRt0',
    appId: '1:254208556943:web:3810247665b3af1347d5fa',
    messagingSenderId: '254208556943',
    projectId: 'adminpanel-c5c41',
    authDomain: 'adminpanel-c5c41.firebaseapp.com',
    storageBucket: 'adminpanel-c5c41.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQMaYUDx7-G-D_8-oupwgvYqVzv9G6Kyc',
    appId: '1:254208556943:android:997a2a4e7744b24547d5fa',
    messagingSenderId: '254208556943',
    projectId: 'adminpanel-c5c41',
    storageBucket: 'adminpanel-c5c41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNtAj9lsSEhz2aJDGR8EXhespVth5Opb4',
    appId: '1:254208556943:ios:c9d0ada79ab12de347d5fa',
    messagingSenderId: '254208556943',
    projectId: 'adminpanel-c5c41',
    storageBucket: 'adminpanel-c5c41.firebasestorage.app',
    iosBundleId: 'com.example.desktopWebApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNtAj9lsSEhz2aJDGR8EXhespVth5Opb4',
    appId: '1:254208556943:ios:c9d0ada79ab12de347d5fa',
    messagingSenderId: '254208556943',
    projectId: 'adminpanel-c5c41',
    storageBucket: 'adminpanel-c5c41.firebasestorage.app',
    iosBundleId: 'com.example.desktopWebApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0oDjc489B4AmTYfmJfarpaFoX1rbVRt0',
    appId: '1:254208556943:web:9868614f7e04dc0047d5fa',
    messagingSenderId: '254208556943',
    projectId: 'adminpanel-c5c41',
    authDomain: 'adminpanel-c5c41.firebaseapp.com',
    storageBucket: 'adminpanel-c5c41.firebasestorage.app',
  );

}